version: '3.8'

services:
  web-app:
    image: web-app
    build: .
    volumes:
      - ./Main_menu.aspx:/app/Main_menu.aspx
      - ./Main_menu.aspx.vb:/app/Main_menu.aspx.vb
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-app